/* Define testing order */
require('babel-polyfill')

require('./account.spec')
require('./customer.spec')
require('./order.spec')
require('./payment.spec')
require('./refund.spec')
require('./multiorder.spec')
require('./multipayment.spec')
require('./notification.spec')
require('./bankAccount.spec')
require('./escrow.spec')
require('./webhook.spec')
require('./connect.spec')
require('./plan.spec')
require('./subscriber.spec')
require('./subscription.spec')
require('./coupon.spec')
require('./transfer.spec')
require('./balance.spec')
