/* Define testing order */
require('./connect.spec.js')
require('./notification.spec.js')
require('./webhook.spec.js')
require('./customer.spec.js')
require('./order.spec.js')
require('./payment.spec.js')
require('./plan.spec.js')
require('./subscriber.spec.js')
require('./subscription.spec.js')
require('./coupon.spec.js')
